// Generated by dts-bundle-generator v9.5.1

export declare function health(): Promise<{
	status: string;
	timestamp: string;
	db: string;
	env: "development" | "production";
}>;
export declare function seed(): Promise<{
	success: boolean;
}>;
export declare function getMenuItems(): Promise<{
	id: string;
	name: string;
	category: string;
	price: number;
	unit: string;
	description: string;
	image: string | null;
	createdAt: Date;
}[]>;
export declare function getMenuItemsByCategory(category: string): Promise<{
	id: string;
	name: string;
	category: string;
	price: number;
	unit: string;
	description: string;
	image: string | null;
	createdAt: Date;
}[]>;
export declare function createBooking(input: {
	name: string;
	phone: string;
	email?: string;
	date: string;
	time: string;
	guests: number;
	comment?: string;
}): Promise<{
	id: string;
	name: string;
	createdAt: Date;
	date: string;
	userId: string | null;
	phone: string;
	email: string | null;
	time: string;
	guests: number;
	comment: string | null;
	status: string;
}>;
export declare function getBookings(): Promise<{
	id: string;
	name: string;
	createdAt: Date;
	date: string;
	userId: string | null;
	phone: string;
	email: string | null;
	time: string;
	guests: number;
	comment: string | null;
	status: string;
}[]>;
export declare function updateBookingStatus(id: string, status: string): Promise<{
	id: string;
	name: string;
	createdAt: Date;
	date: string;
	userId: string | null;
	phone: string;
	email: string | null;
	time: string;
	guests: number;
	comment: string | null;
	status: string;
}>;
export declare function createOrder(input: {
	name: string;
	phone: string;
	email?: string;
	address?: string;
	pickupTime?: string;
	comment?: string;
	items: Array<{
		menuItemId: string;
		quantity: number;
		price: number;
	}>;
}): Promise<{
	items: ({
		menuItem: {
			id: string;
			name: string;
			category: string;
			price: number;
			unit: string;
			description: string;
			image: string | null;
			createdAt: Date;
		};
	} & {
		id: string;
		price: number;
		quantity: number;
		menuItemId: string;
		orderId: string;
	})[];
} & {
	id: string;
	name: string;
	createdAt: Date;
	userId: string | null;
	phone: string;
	email: string | null;
	comment: string | null;
	status: string;
	address: string | null;
	pickupTime: string | null;
	total: number;
}>;
export declare function getOrders(): Promise<({
	items: ({
		menuItem: {
			id: string;
			name: string;
			category: string;
			price: number;
			unit: string;
			description: string;
			image: string | null;
			createdAt: Date;
		};
	} & {
		id: string;
		price: number;
		quantity: number;
		menuItemId: string;
		orderId: string;
	})[];
} & {
	id: string;
	name: string;
	createdAt: Date;
	userId: string | null;
	phone: string;
	email: string | null;
	comment: string | null;
	status: string;
	address: string | null;
	pickupTime: string | null;
	total: number;
})[]>;
export declare function updateOrderStatus(id: string, status: string): Promise<{
	id: string;
	name: string;
	createdAt: Date;
	userId: string | null;
	phone: string;
	email: string | null;
	comment: string | null;
	status: string;
	address: string | null;
	pickupTime: string | null;
	total: number;
}>;
export declare function getReviews(): Promise<{
	id: string;
	createdAt: Date;
	author: string;
	rating: number;
	text: string;
	date: string;
}[]>;
export declare function createReview(input: {
	author: string;
	rating: number;
	text: string;
	date: string;
}): Promise<{
	id: string;
	createdAt: Date;
	author: string;
	rating: number;
	text: string;
	date: string;
}>;

export {};
